sageone:
  client_id: 'YOUR_CLIENT_ID'
  client_secret: 'YOUR_CLIENT_SECRET'
  apim_subscription_key: 'YOUR_APIM_SUBSCRIPTION_KEY'
  callback_url: 'http://localhost:3000/auth/callback'
  auth_endpoint: 'https://www.sageone.com/oauth2/auth/central'
  token_endpoint:
    ca: 'https://oauth.na.sageone.com/token'
    de: 'https://oauth.eu.sageone.com/token'
    es: 'https://oauth.eu.sageone.com/token'
    fr: 'https://oauth.eu.sageone.com/token'
    gb: 'https://app.sageone.com/oauth2/token'
    ie: 'https://app.sageone.com/oauth2/token'
    us: 'https://oauth.na.sageone.com/token'
  base_endpoint:
    ca: 'https://api.columbus.sage.com/ca/sageone'
    de: 'https://api.columbus.sage.com/de/sageone'
    es: 'https://api.columbus.sage.com/es/sageone'
    fr: 'https://api.columbus.sage.com/fr/sageone'
    gb: 'https://api.columbus.sage.com/uki/sageone'
    ie: 'https://api.columbus.sage.com/uki/sageone'
    us: 'https://api.columbus.sage.com/us/sageone'
