sageone:
  client_id: 'YOUR_CLIENT_ID'
  client_secret: 'YOUR_CLIENT_SECRET'
  signing_secret: 'YOUR_SIGNING_SECRET'
  callback_url: 'YOUR_CALLBACK_URL'
  auth_endpoint: 'https://www.sageone.com/oauth2/auth'
  token_endpoint: 'https://api.sageone.com/oauth2/token'
  base_endpoint: 'https://api.sageone.com'
