sage_accounting:
  client_id: 'YOUR_CLIENT_ID'
  client_secret: 'YOUR_CLIENT_SECRET'
  callback_url: 'http://localhost:3000/auth/callback'
  auth_endpoint: 'https://www.sageone.com/oauth2/auth/central'
  token_endpoint: 'https://oauth.accounting.sage.com/token'
  base_endpoint: 'https://api.accounting.sage.com/v3.1'
